### PR TITLE
update for sc3.9

### PR DESCRIPTION
**Pull request by redFrik**

### CODE REVIEW

**Comment by dyfer** [comment]
hey @redFrik, looks like this PR has been sitting for a while, would you like this to be merged now?

**Comment by redFrik** [comment]
yes, please.  thanks.
although i'm not sure it matters. it was long ago i got help to change the main quark directory listing so that it points to my own fork.
ideally i guess this reprository should move over but i don't know how to do that.

**Comment by dyfer** [comment]
Oh, I see. In that case we could simply archive this repo and point to your fork. Would that be okay? Would you still want to update it? I don't think that's needed, unless someone uses the old link, which I guess is unlikely if the quarks directory has been updated some time ago.

**Comment by redFrik** [comment]
archiving sounds good.  not that i really know how that works but happy to learn.  do tell if that's something i can do.

all these also have the same problem...
https://github.com/supercollider-quarks/PopUpTreeMenu
https://github.com/supercollider-quarks/redSys
https://github.com/supercollider-quarks/redSampler
https://github.com/supercollider-quarks/TraerPhysics
https://github.com/supercollider-quarks/Ease
https://github.com/supercollider-quarks/Bjorklund
https://github.com/supercollider-quarks/UGenPatterns
https://github.com/supercollider-quarks/redMst
https://github.com/supercollider-quarks/redGrain
i wrote them and since long the directory.txt is pointing to my forks at github.com/redFrik
so if not too much work perhaps archive them all while you're at it?

and as a sidenote i now saw that https://github.com/supercollider-quarks/AudioMulchClock has a pending pull request.

thanks

**Comment by dyfer** [comment]
> archiving sounds good. not that i really know how that works but happy to learn. do tell if that's something i can do.

You can do it, if you have write access to this repo.
If you go to the Settings tab in Github web interface, at the bottom of that "Options" page you can find "Danger zone". There you can archive the repository, which makes it read-only. I think it would be worth adding the your fork's address in the "about" section so that it's easy to find. Let me know if you can do it or if I should do it.

**Comment by redFrik** [comment]
sorry i'd do it but don't have access.  so grateful if you'd do it.

**Comment by dyfer** [comment]
@redFrik I have added a note to all the repos you've listed linking to your forks and I have archived them all. I'll now close this issue and will archive this repo as well. Please let me know in case there are any issues with the archiving process, access etc - I hope that this won't affect anyone adversely.

**Pull request closed without merging**
